name: Deploy Firebase Functions
on:
  push:
    branches:
      - master
    paths:
      - 'packages/@ergin/hh-report-firebase-functions/**'
      - 'packages/@ergin/hh-report-common/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: packages/@lergin/hh-report-firebase-functions
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
